---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
      - 'master'
      - release/*
  pull_request:
    branches:
      - master
      - release/*
    paths-ignore:
      - '**/*.js' # Disable since ESLint is used and v9 config is incompatible
      - '**/*.mjs'
      - '**/*.cjs'
      - '**/*.min.js'

###############
# Set the Job #
###############
jobs:
  build:
    strategy:
      fail-fast: false
      # matrix:
      #   language:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: false
          EDITORCONFIG_FILE_NAME: '.editorconfig'
          JAVASCRIPT_ES_CONFIG_FILE: 'eslint.coonfig.js'
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_XML: true
          VALIDATE_MD: true
          VALIDATE_HTML: true
          VALIDATE_BASH: true
          VALIDATE_PERL: true
          VALIDATE_PHP_BUILTIN: true
          VALIDATE_PYTHON: true
          VALIDATE_RUBY: true
          VALIDATE_COFFEE: true
          VALIDATE_ANSIBLE: true
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          VALIDATE_DOCKER: true
          VALIDATE_GO: true
          VALIDATE_TERRAFORM: true
          VALIDATE_CSS: true
          ANSIBLE_DIRECTORY:
          ACTIONS_RUNNER_DEBUG: true
          DEFAULT_WORKSPACE:
